### ISSUE TITLE
Put PHONY before every target 

### ISSUE THREAD

**Issue by hanzei** [mattermost/mmctl#136]
Every target should have a `PHONY` before it. With this in place, the incomplete `PHONY` list at the start can be removed.

_Originally posted by @hanzei in https://github.com/mattermost/mmctl/pull/131_

**Comment by attiss** [comment]
Hey @hanzei ,

I'd be happy to get this done.

**Comment by hanzei** [comment]
Awesome, thanks @attiss :+1:
