### ISSUE TITLE
Update documentation for auth

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mmctl#15]
There is not possible to run such CLI:

https://github.com/mattermost/mmctl#access-tokens says:

$ mmctl auth login https://community.mattermost.com --name community **--username** my-username --access-token MY_ACCESS_TOKEN

The command needs to have the --username variable removed.

IE:
`➜ mmctl auth login https://chat.uhlhosting.ch --name UHL --username cosmin --access-token xxxxxxxxxxxxxxxxxxxxxxx 
Error: You must use --access-token or --username, but not both`

When running without --username:

`  credentials for UHL: Personal Access Token@https://chat.uhlhosting.ch stored`

**Comment by jasonblais** [comment]
cc @mgdelacroix on above

**Comment by mgdelacroix** [comment]
Thanks for the report, @uhlhosting! I've sent #16 to remove the `--username` parameter from both the README and the command documentation
