### ISSUE TITLE
Add polibility to split or copy channel

### ISSUE THREAD

**Issue by fzeiser** [mattermost/mmctl#154]
Would it be possible to add a command `channel copy` to copy a channel. I frequently end up in a situation where the tasks grow, much like described in [Organizing Mattermost](https://docs.mattermost.com/help/getting-started/organizing.html).

> For example, you might begin with a general “Marketing” channel. As conversations progress, you might divide that channel into: “Marketing: Website”, “Marketing: Social Media”, “Marketing: General”.

However, when splitting `Marketing` into `Marketing: Website` and `Marketing: Social Media`, I might want to keep the history of the old channel  `Marketing` in both new channels. Especially so, if I might later create a new team to exclusively work on `Marketing: Social Media`. Fortunately, the api would already provide `channel move` for the last task.

**Comment by isacikgoz** [comment]
Hey @fzeiser this would not be possible as the posts need to be duplicated and essentially creating new posts behalf of users wouldn't be a great experience. Closing the issue for now, feel free to re-open if you think otherwise.

**Comment by agbuckley** [comment]
I just hit a similar use-case for splitting a channel whose scope has ended up too broad, but wanting to keep the original channel's subscribers on the new ones. Maybe cloning the existing subscriber list to a new name, with an optional pop-up menu to opt-in for history retention? Not sure of the best UI, but splitting topic without losing the subscribers from one of the channels would be pretty useful.
