### ISSUE TITLE
v5.22.0 and v5.23.0 tagged the same commit

### ISSUE THREAD

**Issue by chenrui333** [mattermost/mmctl#155]
I just noticed that the most release (v5.23.0) tagged the same commit as release v5.22.0. Can you double verify the release flow at your end?

**Comment by mgdelacroix** [comment]
Hi @chenrui333! Thanks for pointing this out. The version `5.23.0` of `mmctl` has not been released yet. It will be released at the same time than the `mattermost-server` version, but our current release process needs to have this tag created beforehand to be able to bundle it with the server.

We are considering other options to improve our release process and avoid the release artefact being tagged before the actual release is produced.

**Comment by chenrui333** [comment]
@mgdelacroix that makes sense, thanks!

Closing the issue.
