### ISSUE TITLE
[feature request] list teams of a user or users of a team

### ISSUE THREAD

**Issue by svelle** [mattermost/mmctl#195]
Something like `mmctl team users list` that lists all the users of a team and `mmctl user teams list` that lists all teams of a user.
Especially the latter doesn't have any representation in the UI of the webapp afaik.

**Comment by mgdelacroix** [comment]
For the former, do you think reusing the `mmctl user list` would suffice with a `--team TEAMNAME` flag?

As for the latter, to keep a consistent schema, we could do a `mmctl team list --user USERNAME` flag.

**Comment by svelle** [comment]
sure I'm definitely not set on the syntax here. absolutely down with going with what's consistent.

**Comment by mgdelacroix** [comment]
Great! I created a ticket to follow up on the request: https://mattermost.atlassian.net/browse/MM-28194

**Comment by isacikgoz** [comment]
Fixed with #239
