### ISSUE TITLE
mmctl 5.28.0 release sha got changed?

### ISSUE THREAD

**Issue by chenrui333** [mattermost/mmctl#251]
👋  Per the most recent [go 1.15.3 upgrade](https://github.com/Homebrew/homebrew-core/pull/62909), we found that the mmctl release sha got changed.

So I am trying to fix in [this PR](https://github.com/Homebrew/homebrew-core/pull/63053).

Raising this issue to confirm if that is intended. Thanks!

**Comment by mgdelacroix** [comment]
Hi @chenrui333! Apologies for the late response. Yes, the change was intended, and the PR is now pointing to the right commit.

Thanks for taking care of the change!
