### ISSUE TITLE
auth set not working - "Error cannot save the credentials"

### ISSUE THREAD

**Issue by icelander** [mattermost/mmctl#286]
## Environment

 - mmctl version: 5.30.0 (installed with Homebrew)
 - Workstation OS:   macOS Catalina 10.15.7

## Steps to Reproduce

1. Run `mmctl auth set name`

## Expected Behavior

Authentication credentials are changed

## Observed Behavior

Credentials are not changed, shows this error:

```
Error: cannot save the credentials: open /Users/paul/.mmctl/.mmctl: not a directory
Usage:
  mmctl auth set [server name] [flags]

Examples:
  auth set local-server

Flags:
  -h, --help   help for set

Global Flags:
      --config string                path to search for '.mmctl' configuration file (default "$HOME/.config/mmctl")
      --format string                the format of the command output [plain, json] (default "plain")
      --insecure-sha1-intermediate   allows to use insecure TLS protocols, such as SHA-1
      --local                        allows communicating with the server through a unix socket
      --strict                       will only run commands if the mmctl version matches the server one
```

## Steps tried

1. Upgrading `mmctl` to latest version
2. Creating `/Users/paul/.mmctl/` and moving existing config file into it. (This resulted in a different error)
3. It appears that `mmctl auth login` and `mmctl auth renew` also fail

**Comment by mgdelacroix** [comment]
Thanks for the report @icelander! This should be solved by https://github.com/mattermost/mmctl/pull/282

**Comment by icelander** [comment]
Is there a workaround for this? I'm unable to use mmctl at all because of this bug. I tried setting `XDG_CONFIG_HOME` to a bunch of different values and keep getting the same error message.
