### ISSUE TITLE
Git tag commit changed?

### ISSUE THREAD

**Issue by SeekingMeaning** [mattermost/mmctl#301]
Hi, Homebrew maintainer here. I noticed that the commit for the v5.31.0 tag changed from

fc161b2931110a913169a0601f0d9d0a36b1749a

to

689bd041b5aa02183721fda0c4e9a4e3d84fab15

It seems this was to edit some files and update the version number. Is this right?

**Comment by mgdelacroix** [comment]
Hi @SeekingMeaning,

thanks for taking care of the Homebrew release! Yes, this change was intended, mainly to include the updated `mmctl` version before the corresponding `mattermost-server` was released.
