### ISSUE TITLE
mmctl does not work if system user has no /etc/passwd entry (e.g. on OpenShift deployments)

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mmctl#313]
There's a panic when running `mmctl` e.g. on an openshift deployment where you have a random uid, usually with no corresponding `/etc/passwd` entry:

```
I have no name!@mm-openshift-185-6drkz:/mattermost$ id
uid=1000170000 gid=0(root) groups=0(root),1000170000

I have no name!@mm-openshift-185-6drkz:/mattermost$ ./bin/mmctl
panic: user: unknown userid 1000170000

goroutine 1 [running]:
github.com/mattermost/mmctl/commands.init.1()
        /builds/mattermost/ci-only/mmctl/commands/auth_utils.go:44 +0x74
```

Especially in `--local` mode there should not be any need to look up anything about the current linux system user, and outside local mode `$HOME` could be read as an alternative.

**Comment by isacikgoz** [comment]
Created a ticket for this https://mattermost.atlassian.net/browse/MM-33055 👍

**Comment by isacikgoz** [comment]
The ticket has been marked as won't fix, hence closing the issue. It seems like we have a hard requirement for a user to exist in the system.

**Comment by ThiefMaster** [comment]
Sorry but what's the technical reason for this? I don't see why a simple tool like mmctl would not work without an `/etc/passwd` entry... In `--local` mode there's no need to do anything with the current user or its home dir.
