### ISSUE TITLE
[Feature Request] create a random password and send it to mail.

### ISSUE THREAD

**Issue by hkpanchani** [mattermost/mmctl#314]
Generate random password and send password to mail via CLI..
Or generate an URL and send it to mail for first time user login.

**Comment by isacikgoz** [comment]
Hey @hkpanchani, thanks for the feedback! We already have `mmctl user reset_password user@example.com` command, do you mean something different apart from that? Could you elaborate your request?

**Comment by hkpanchani** [comment]
while creating new user with mmctl user create_user.
Generate user with random password rather than passing it as params in mmctl and send the password or signup link in users email. so i dont have to share password to them manually.

**Comment by isacikgoz** [comment]
Closing this as we don't create the passwords creating new user process. I'd suggest using a random string genarator in the script.
