### ISSUE TITLE
[Feature Request] Add `config patch` command

### ISSUE THREAD

**Issue by icelander** [mattermost/mmctl#319]
The command would look like this:

```bash
mmctl config patch <FILENAME>
```

And would emulate this CURL command to apply the configuration settings in the supplied JSON file:

```bash
curl -X PUT\
 -H "Content-Type: application/json"\
 -H "Authorization: Bearer $TOKEN"\
 -d @./patch_config.json\
 https://mattermost.example.com/api/v4/config/patch
```

**Comment by isacikgoz** [comment]
Created the ticket https://mattermost.atlassian.net/browse/MM-33052 👍

**Comment by ChandanChainani** [comment]
@isacikgoz Please close the issue since it is done the [`PR`](https://github.com/mattermost/mmctl/pull/331) for this issue has been merged and changes are available in master branch
