### ISSUE TITLE
Error: unknown flag: --local-socket-path

### ISSUE THREAD

**Issue by chuhn** [mattermost/mmctl#323]
The [documentation](https://docs.mattermost.com/administration/config-settings.html#enable-local-mode-socket-location) claims that the option `--local-socket-path` can be used to point `mmctl` to the right server socket. Anyhow `mmctl  --local --local-socket-path … cmd` (from Mattermost 5.31.1 team edition tar ball) gives me:
> Error: unknown flag: --local-socket-path

I checked that the socket has been created by the server with the proper owner and permissions (`0600`).

**Comment by chuhn** [comment]
FWIW the default location of the lockfile `/var/tmp/…` is a very bad choice:
1. `/var/tmp` is usually world-readable which exposes mattermost to symlink attacks etc.
2. If mattermost is running as a systemd unit with `PrivateTmp=yes` (→ to circumvent the dangers of 1.), the socket becomes inaccessible to `mmctl`

**Comment by isacikgoz** [comment]
Hey @chuhn thanks for the feedback! The `local-socket-path` is not a flag, it should be used as an env. variable. Application will take `MMCTL_LOCAL_SOCKET_PATH` variable into account. Also, `/var/tmp/… ` is the default value, you may want to set another file in the Server Configuration. I created a PR [here](https://github.com/mattermost/docs/pull/4366) to clarify this. Sorry about the confusion here!

**Comment by isacikgoz** [comment]
Updated the docs. Closing as https://github.com/mattermost/docs/pull/4366 is merged.
