### ISSUE TITLE
go get installation error on debian 10

### ISSUE THREAD

**Issue by Apfelwurm** [mattermost/mmctl#347]
Hi, when i try to install mmctl using go get on debian 10 it downloads a lot of stuff but then crashes with:

`github.com/mattermost/mmctl imports
	github.com/mattermost/mmctl/commands imports
	github.com/mattermost/mattermost-server/v5/shared/mlog/human: cannot find module providing package github.com/mattermost/mattermost-server/v5/shared/mlog/human`

The last successful build i installed was on the 5.03.2021, so i looked into which version this could be and tried to use 

`go get -u github.com/mattermost/mmctl@release-5.32`

but here occurs an other problem:

`# github.com/mattermost/mmctl/commands
pkg/mod/github.com/mattermost/mmctl@v0.0.0-20210128094132-5215188aab55/commands/init.go:48:13: cannot use c (type *model.Client4) as type client.Client in argument to fn:
	*model.Client4 does not implement client.Client (wrong type for GetPostsForChannel method)
		have GetPostsForChannel(string, int, int, string, bool) (*model.PostList, *model.Response)
		want GetPostsForChannel(string, int, int, string) (*model.PostList, *model.Response)
pkg/mod/github.com/mattermost/mmctl@v0.0.0-20210128094132-5215188aab55/commands/init.go:64:12: cannot use c (type *model.Client4) as type client.Client in argument to fn:
	*model.Client4 does not implement client.Client (wrong type for GetPostsForChannel method)
		have GetPostsForChannel(string, int, int, string, bool) (*model.PostList, *model.Response)
		want GetPostsForChannel(string, int, int, string) (*model.PostList, *model.Response)`

can someone give me a hint what i missed out in the mean time?
thanks!

**Comment by isacikgoz** [comment]
Hey @Apfelwurm we don't recommend using `-u` flag while installing as it updates the dependencies at causes errors. Can you try `go install github.com/mattermost/mmctl@latest` instead? Sorry for the delay to reply this 🙏

**Comment by Apfelwurm** [comment]
Thanks, that fixed the problems :)
no problem, for sure you have enough stuff to do!
