### ISSUE TITLE
get posts as JSON

### ISSUE THREAD

**Issue by laurentperrinet** [mattermost/mmctl#352]
I achieve getting posts as a text stdout:

```
❯ mmctl post list mychannel:test 
[laurent.perrinet] hi
[laurent.perrinet] test 
```

but asking to have it in JSON format outputs the same result :
```
❯ mmctl post list mychannel:test --format json
[laurent.perrinet] hi
[laurent.perrinet] test 
```

any way to get a JSON format (with the metadata related to each post)?

cheers,
Laurent

**Comment by mgdelacroix** [comment]
Hi @laurentperrinet! Thanks for the report, the `post list` command wasn't taking the `--format` flag into account, so I've just sent a patch to enable its support.

Best!!
