### ISSUE TITLE
[Feature Request] Purge modified and deleted messages

### ISSUE THREAD

**Issue by yannicka** [mattermost/mmctl#365]
It would be nice to have a command that deletes modified messages (only the last version of the message would be kept) and deleted messages from the database.

**Comment by isacikgoz** [comment]
Hey @yannicka thanks for the feedback! I'm going to create a ticket to discuss this feature internally. https://mattermost.atlassian.net/browse/MM-40524

**Comment by isacikgoz** [comment]
Hey @yannicka we do not store the history of edited messages, I think the only possible thing for this request would be deleting edited posts from database. Would it be a valuable feature for you?

**Comment by yannicka** [comment]
The last time I looked, there were all the messages in the database, even the modified ones. If this is no longer the case, then this request is no longer relevant. If it is still the case, it might be interesting to have a cleanup option.

**Comment by hanzei** [comment]
Closing this issue as it's getting tracked via https://mattermost.atlassian.net/browse/MM-40524
