### ISSUE TITLE
mmctl version not exposed to Go tooling

### ISSUE THREAD

**Issue by twnk** [mattermost/mmctl#398]
While mmctl has versions corresponding to Mattermost versions, these are not exposed in the way the tool is released. This means you can't do `go install github.com/mattermost/mmctl@v5.39.0` for example. 

See e.g. https://pkg.go.dev/github.com/mattermost/mmctl which can only identify two versions, both. 0.0.0

>v0.0.0-20210920163629-405371aabf8f
>Sep 20, 2021
>v0.0.0-20210916144103-24c8d34e1833
>Sep 16, 2021

**Comment by isacikgoz** [comment]
This is great feedback @twnk We pack `mmctl` with the mattermost release but haven't considered doing individual releases for mmctl. I'll raise your issue internally.

**Comment by isacikgoz** [comment]
We added this https://github.com/mattermost/mmctl/pull/428 but it won't be supporting for v6 as the v6 tag does not have a version path in go.mod. This will be available in future major versions. Hopefully v7 at summer this year!

**Comment by hanzei** [comment]
`mmctl` now lives in https://github.com/mattermost/mattermost/tree/master/server/cmd/mmctl and need to be installed via the repo.
