### ISSUE TITLE
Error message confusing when new user password doesn't meet requirements

### ISSUE THREAD

**Issue by Eric-Girard** [mattermost/mmctl#399]
While using mmctl to create a user, if the password provided doesn't meet the requirement mmctrl returns the following error message

_Error: Unable to create user. Error: : Login failed because of invalid password._  

This can be misleading to think that the credentials provided to login in the mattermost instance are invalid 

It would be much more user friendly to provide a clear message stating that the password provided for the new user is invalid

**Comment by Avlyssna** [comment]
Very confusing at first - and still an issue! If I hadn't found this issue, I would've continued wondering why my password was incorrect.

**Comment by hanzei** [comment]
See https://github.com/mattermost/mattermost/issues/19912
