### ISSUE TITLE
There is no way to list archived private channels if the user isn't the member of its channel

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mmctl#401]
# Summary
Executing `mmctl channel list team` doesn't list archived private channels if the user who run the command isn't member of its channel, even if the user is system admin.  Not showing private channels that user isn't a member of is often the right thing to do, but there are times when system administrator want to list all channels including those the admin aren't participating in.

---

Up to v5.39, I can list all channels except for direct channels by `mattermost channel` command, because the command call `GetAll(team.id)` internally. But `mattermost channel` has removed in v6.0.
https://github.com/mattermost/mattermost-server/blob/release-5.39/cmd/mattermost/commands/channel.go#L482

**Comment by isacikgoz** [comment]
Hey @kaakaa thanks for the feedback! We have an API call `GetDeletedChannelsForTeam` while listing the channels but I can confirm that it does not list if the admin is not a member of archived private channel. Ticket created https://mattermost.atlassian.net/browse/MM-39918 here.

**Comment by hanzei** [comment]
Tracking this feature request via https://github.com/mattermost/mattermost/issues/19913
