### ISSUE TITLE
Verify user email command description is misleading 

### ISSUE THREAD

**Issue by twnk** [mattermost/mmctl#405]
https://github.com/mattermost/mmctl/blob/d9ba9200bd47addb6b7fe8d757de95ab8af9e594/commands/user.go#L170

There's a big difference between “trigger a verification email” and “irrevocably mark a user as verified without performing any verification steps”. “Verify the user's email address” to me implies causing a verification flow rather than completing one! I think it should be amended to say “Mark user's email as verified.” or similar.

**Comment by isacikgoz** [comment]
Hey @twnk thanks for the feedback! We verify user email by a token sent to their email. And we verify the user with the token via ` VerifyUserEmail(token string)` method. And this model skips that extra step that needs to go through user effort. I see your point, I think we should add a better documentation here.
