### ISSUE TITLE
mmctl 6.2.0 is gone?

### ISSUE THREAD

**Issue by iMichka** [mattermost/mmctl#417]
Hi.

Homebrew maintainer here (homebrew is the missing package manager for macOS and Linux).
We started shipping the 6.2.0 release some time ago, but it looks like the tag is gone. Is this release gone?
Should we go back to 6.1.0?

Related issue: https://github.com/Homebrew/homebrew-core/pull/91184

Thanks

**Comment by chenrui333** [comment]
cc @cpanato

**Comment by cpanato** [comment]
@iMichka mattermost release 6.2.0 is not released yet, as soon 6.2.0 is released we will create and release the mmctl 6.2.0 as well

**Comment by cpanato** [comment]
it is out now https://github.com/mattermost/mmctl/releases/tag/v6.2.0
