### ISSUE TITLE
authToken is stored unencypted in config file

### ISSUE THREAD

**Issue by jmairboeck** [mattermost/mmctl#465]
I have noticed that the authToken is stored as-is (unencrypted) in the configuration file. Maybe this could be improved somehow? (e.g. using platform specific APIs such as WinCrypt, macOS keychain, KDE Wallet, Gnome keyring etc.)

I have not tested a password, as our server doesn't support that in its current config (using Gitlab for login).

**Comment by isacikgoz** [comment]
Hey @jmairboeck! thanks for the feedback! We will be discussing this but I'm a little cautious about this as we don't want to have hard dependencies on a specific OS. These APIs can change sporadically and may cause a failure in the future. Created the ticket here anyway: https://mattermost.atlassian.net/browse/MM-43066

**Comment by agnivade** [comment]
@jupenur - any thoughts on the above :point_up:

**Comment by jupenur** [comment]
Hey @jmairboeck that's correct, tokens are stored in cleartext. Do note however, that mmctl does *not* store passwords -- instead, if you initiate a session using password auth, the password is only used to retrieve a token from the server -- so there is no risk of password exposure through the unencrypted credential store.

The cleartext storage matches the behavior of many browsers' cookie jars: Chrome does encrypt its cookies, but Firefox and Safari both store cookies in cleartext in the file system. Attempting to protect tokens in mmctl by encrypting them would add very little, when similar tokens are accessible in the cookie jar anyway. Combined with the challenge of platform-specificity @isacikgoz mentioned, it likely wouldn't make sense to add an encryption layer to the credential store in mmctl.

That's my thinking anyway.
