### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by ru2mm** [mattermost/mmctl#525]
Could you add a build target for FreeBSD in your next releases?

Thank you.

**Comment by isacikgoz** [comment]
Hey @ru2mm currently FreeBSD builds are maintained by the community hence we can't include them in the official release bundles. On `mmctl` end, it should be fairly easy to use `go install` utility to build your own binary on FreeBSD. If you hit any problem on compiling please let us know. I'm now closing the issue but feel free to re-open if you feel this needs further discussion. Thanks!
