### ISSUE TITLE
unknown command "import" for "mmctl"

### ISSUE THREAD

**Issue by ChenSun-Phys** [mattermost/mmctl#545]
It seems that the import command gets deprecated. When I tried to import an upload, I got 

> Error: unknown command "import" for "mmctl"
> Run 'mmctl --help' for usage.
>

It `import` now part of some other command?

**Comment by isacikgoz** [comment]
As of `v7.1.2` it's still supported. Which version are you having this error? @ChenSun-Phys

**Comment by ChenSun-Phys** [comment]
I was using the mmctl that comes with the Mattermost server. I later realized that the server itself, being Mattermost 5.x was out-dated. After installing mmctl separately, the import directive works out-of-box. In case anyone is curious, the current mmctl can import to both Mattermost 5 (I forgot the subversion as I later updated it) and Mattermost 7.1.2.
