### ISSUE TITLE
could not check version mismatch: incorrect server version format

### ISSUE THREAD

**Issue by vaskosmihaylov** [mattermost/mmctl#551]
Hello guys,

This is a continuation of the thread in the [528](https://github.com/mattermost/mmctl/issues/528) issue.

### Setup

```
- CentOS 8 Stream
- Mattermost server 7.2.0 
- Postgres 13
- Apache/2.4.37 as a proxy in front of MM server 
```
### Mattermost installation

- The MM server has been installed by following the docs at https://docs.mattermost.com/install/install-rhel-8.html, however, these steps have been wrapped in a Puppet module for easier installation.

### The problem:

```
bash-4.4$ ./mmctl user list
Error: could not check version mismatch: incorrect server version format
```
This happens for most of the mmctl commands.  The version are identical:

```
bash-4.4$ ./mmctl version
mmctl:
Version:	v7.2.0
```
```
bash-4.4$ ./mattermost version
Version: 7.2.0
```
I would like to point out that I first notice the issue on MM version 7.0.1 and mmctl version 7.0.1. After that, I thought if I upgrade to 7.2.0 the version mismatch problem should be resolved. 

I have authenticated successfully towards the remote MM instance via user and pass:

```
bash-4.4$ ./mmctl auth list

    | Active |   Name | Username |                       InstanceURL |
    |--------|--------|----------|-----------------------------------|
    |      * | DPX-MM | username | https://localhost |
```
Lastly, no [local mode ](https://docs.mattermost.com/manage/mmctl-command-line-tool.html#local-mode)is enabled 

The solution I can think of is to compile the mmctl anew from source. Any other suggestions are more than welcome.

**Comment by isacikgoz** [comment]
Hey @vaskosmihaylov thanks for the feedback!

Can you provide the `X-Version-Id` header in the response when you hit the `<your_mattermost_host>/api/v4/users/me`?

cc @agnivade

**Comment by vaskosmihaylov** [comment]
Thank you for the help @isacikgoz. Here is the X-Version-Id header as requested:

```
bash-4.4$ curl -i -H 'Authorization: Bearer hidden' http://localhost:8065/api/v4/users/me | grep X-Version-

X-Version-Id: 7.2.0.7.2.0.858fc5319ba7e279a1bd6865e9e65fbd.false
```

I would like to note if I enable the local mode **mmctl** starts to work as intended:

```
bash-4.4$ ./mmctl user search 'vasko.mihaylov' --local | grep username
username: vasko.mihaylov
```

**Comment by isacikgoz** [comment]
> bash-4.4$ ./mmctl auth list
> 
>     | Active |   Name | Username |                       InstanceURL |
>     |--------|--------|----------|-----------------------------------|
>     |      * | DPX-MM | username | https://localhost |
> ```
> 

@vaskosmihaylov Uh, gotcha.. It seems like you didn't specified the correct port on your host, that's why it's failing I guess. Because when you hit ` http://localhost:8065/api/v4/users/me`,  it's correctly returning the header. The tool is parsing that header so I couldn't see any possible errors over there. Can you try to specify `https://localhost:8065` while logging in with `mmctl`?

**Comment by vaskosmihaylov** [comment]
Thank you, @isacikgoz. Indeed specifying the port when I log in with **mmctl** works. Maybe it would be a good idea to update the README as well and add the port when you initially authenticate.
