### ISSUE TITLE
[feature request] channel make_public

### ISSUE THREAD

**Issue by elyscape** [mattermost/mmctl#61]
`mmctl` has `channel make_private` to make public channels private, but no opposing `channel make_public` command.

**Comment by elyscape** [comment]
Alternatively, these could be combined into a `channel edit` command that would also support modifying the channel name, display name, header, etc.

**Comment by tw-ayush** [comment]
where is the corresponding code in the repo?

**Comment by akshaychhajed** [comment]
hello @tw-ayush,
Code for mmctl can be found here https://github.com/mattermost/mmctl/blob/master/commands/channel.go#L325

**Comment by ChandanChainani** [comment]
@isacikgoz This issue can be closed since it is type of question which is resolved
