### ISSUE TITLE
Virustotal BitDefenderTheta detect Gen:NN.Mirai.36344

### ISSUE THREAD

**Issue by brrrr66** [mattermost/mmctl#645]
Hi
Can you tell me if this trigger is false?
v7.9.0 https://www.virustotal.com/gui/file/4ae7680fb1f8b4f9d039dd787e1a66e5f6f69eff34776c9fb61f4aa21c6f1df6/detection
I also checked v7.8.1, there is also a trigger.
On version v7.4.1 everything is clean.
https://www.virustotal.com/gui/file/0b5d1c3584428d048127672c032d4dae9033e667cf81ec7cd35d6bf5f6d83b2d?nocache=1

**Comment by hanzei** [comment]
Thanks for the report @brrrr66.

Go is a language often used to write Maleware. False positives like the one you linked happen with any go binary from time to time.
