### ISSUE TITLE
README installation instructions install an old version of `mmctl`

### ISSUE THREAD

**Issue by barrettj12** [mattermost/mmctl#671]
The README says:
https://github.com/mattermost/mmctl/blob/dacf19cdd5fb8d3dbc9a7daf954059ce794fa9fb/README.md?plain=1#L13-L17

However, running this command installs a very old version of mmctl (v6.4.2):
```console
$ go install github.com/mattermost/mmctl/v6@master
go: downloading github.com/mattermost/mmctl/v6 v6.4.2-0.20230417141347-dacf19cdd5fb
```

At the very least, the README should give instructions for installing the **latest** version of `mmctl`. Even better would be giving instructions for installing a specified version, e.g. 7.5.2 or 7.8-latest.

**Comment by hanzei** [comment]
The `mmctl` code has moved to https://github.com/mattermost/mattermost/tree/master/server/cmd/mmctl. You can find the new install instructions [here](https://docs.mattermost.com/manage/mmctl-command-line-tool.html#install-mmctl).
