### ISSUE TITLE
Can't set per-page attribute more than 200 at mmctl user list command

### ISSUE THREAD

**Issue by ShalyapinSNET** [mattermost/mmctl#685]
There is --per-page flag at mmctl user list command. Help says that it can be integer. 
But 'mmctl user list --per-page 300' gives me only 200 users. This is confusing.

**Comment by hanzei** [comment]
Good point. The MM server ignores any `per-page` parameter that is greater than 200.

I've opened a HW ticket on the main MM repository: https://github.com/mattermost/mattermost/issues/26022
