### ISSUE TITLE
OSX Issues

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mmctl#8]
I have deployed as for instructions:

`go get -u github.com/mattermost/mmctl`

Followed by:

`source <(mmctl completion bash)` | this resulted in: `-bash: mmctl: command not found`

When I run: `source <(/Users/cosmic/go/bin/mmctl completion bash)` with direct location to the executable it works. Maybe some updates in Readme, to avoid confusion, and why are the recommended .bashrc and .profiles and not .bash_profiles? My .bashrc stricly calls .bash_profiles for ex in OSx.

**Comment by amyblais** [comment]
@mgdelacroix FYI on the above
